"""Added field to Tilaus

Revision ID: 1d10ff7eb33
Revises: 42129b3413e
Create Date: 2014-06-28 11:56:55.565604

"""

# revision identifiers, used by Alembic.
revision = '1d10ff7eb33'
down_revision = '42129b3413e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tilaukset', sa.Column('maksuaika', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tilaukset', 'maksuaika')
    ### end Alembic commands ###
