"""empty message

Revision ID: 05611c3d1c30
Revises: f052370cdfa4
Create Date: 2016-03-29 13:14:02.381862

"""

# revision identifiers, used by Alembic.
revision = '05611c3d1c30'
down_revision = 'f052370cdfa4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('huollot', sa.Column('tyyppi_muu_selite', sa.Text(), nullable=True))
    op.add_column('huollot_version', sa.Column('tyyppi_muu_selite', sa.Text(), autoincrement=False, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('huollot_version', 'tyyppi_muu_selite')
    op.drop_column('huollot', 'tyyppi_muu_selite')
    ### end Alembic commands ###
