"""empty message

Revision ID: 114ff7cd394
Revises: 39d57e0bdb4
Create Date: 2015-09-26 18:50:44.220785

"""

# revision identifiers, used by Alembic.
revision = '114ff7cd394'
down_revision = '39d57e0bdb4'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lisatoimenpidehintaluokat',
    sa.Column('hintaluokka', sa.Integer(), nullable=False),
    sa.Column('tunnit', sa.Float(), nullable=True),
    sa.Column('matkat', sa.Float(), nullable=True),
    sa.Column('muut', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('hintaluokka')
    )
    op.drop_table('lisatoimenpidehintaluokka')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lisatoimenpidehintaluokka',
    sa.Column('hintaluokka', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('tunnit', mysql.FLOAT(), nullable=True),
    sa.Column('matkat', mysql.FLOAT(), nullable=True),
    sa.Column('muut', mysql.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('hintaluokka'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('lisatoimenpidehintaluokat')
    ### end Alembic commands ###
