"""empty message

Revision ID: 17da5d1bd91
Revises: None
Create Date: 2014-06-22 01:19:12.567361

"""

# revision identifiers, used by Alembic.
revision = '17da5d1bd91'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
