"""empty message

Revision ID: 182ebb63038
Revises: 352816628c6
Create Date: 2014-08-21 23:01:49.081193

"""

# revision identifiers, used by Alembic.
revision = '182ebb63038'
down_revision = '352816628c6'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('kohteet', sa.Column('osoite', sa.Text(), nullable=True))
    op.add_column('kohteet', sa.Column('postinumero', sa.Text(), nullable=True))
    #op.add_column('kohteet', sa.Column('postitoimipaikka', sa.Text(), nullable=True))
    #op.drop_column('kohteet', 'osoite2')
    op.alter_column('kohteet', 'osoite2', new_column_name='postitoimipaikka', existing_type=sa.Text())
    #op.drop_column('kohteet', 'osoite1')
    op.alter_column('kohteet', 'osoite1', new_column_name='osoite', existing_type=sa.Text())
    #op.add_column('tilaajat', sa.Column('osoite', sa.Text(), nullable=True))
    op.add_column('tilaajat', sa.Column('postinumero', sa.Text(), nullable=True))
    #op.add_column('tilaajat', sa.Column('postitoimipaikka', sa.Text(), nullable=True))
    #op.drop_column('tilaajat', 'osoite2')
    op.alter_column('tilaajat', 'osoite2', new_column_name='postitoimipaikka', existing_type=sa.Text())
    #op.drop_column('tilaajat', 'osoite1')
    op.alter_column('tilaajat', 'osoite1', new_column_name='osoite', existing_type=sa.Text())
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    #op.add_column('tilaajat', sa.Column('osoite1', mysql.TEXT(), nullable=True))
    #op.add_column('tilaajat', sa.Column('osoite2', mysql.TEXT(), nullable=True))
    #op.drop_column('tilaajat', 'postitoimipaikka')
    op.alter_column('tilaajat', 'postitoimipaikka', new_column_name='osoite2', existing_type=sa.Text())
    op.drop_column('tilaajat', 'postinumero')
    #op.drop_column('tilaajat', 'osoite')
    op.alter_column('tilaajat', 'osoite', new_column_name='osoite1', existing_type=sa.Text())
    #op.add_column('kohteet', sa.Column('osoite1', mysql.TEXT(), nullable=True))
    #op.add_column('kohteet', sa.Column('osoite2', mysql.TEXT(), nullable=True))
    #op.drop_column('kohteet', 'postitoimipaikka')
    op.alter_column('kohteet', 'postitoimipaikka', new_column_name='osoite2', existing_type=sa.Text())
    op.drop_column('kohteet', 'postinumero')
    #op.drop_column('kohteet', 'osoite')
    op.alter_column('kohteet', 'osoite', new_column_name='osoite1', existing_type=sa.Text())
    ### end Alembic commands ###
