"""empty message

Revision ID: 19027df648c
Revises: 114ff7cd394
Create Date: 2015-09-26 21:46:38.319066

"""

# revision identifiers, used by Alembic.
revision = '19027df648c'
down_revision = '114ff7cd394'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('huollot', sa.Column('hintaluokka_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'huollot', 'huoltohintaluokat', ['hintaluokka_id'], ['hintaluokka'])
    op.add_column('huollot_version', sa.Column('hintaluokka_id', sa.Integer(), autoincrement=False, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('huollot_version', 'hintaluokka_id')
    op.drop_constraint(None, 'huollot', type_='foreignkey')
    op.drop_column('huollot', 'hintaluokka_id')
    ### end Alembic commands ###
