"""empty message

Revision ID: 1d323e2bdcb
Revises: 182ebb63038
Create Date: 2014-08-21 23:55:02.348266

"""

# revision identifiers, used by Alembic.
revision = '1d323e2bdcb'
down_revision = '182ebb63038'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kohteet', sa.Column('ytunnus', sa.Text(), nullable=True))
    op.add_column('tilaajat', sa.Column('ytunnus', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tilaajat', 'ytunnus')
    op.drop_column('kohteet', 'ytunnus')
    ### end Alembic commands ###
