"""empty message

Revision ID: 2630fa50c62
Revises: 29048b05599
Create Date: 2015-09-14 20:01:45.414748

"""

# revision identifiers, used by Alembic.
revision = '2630fa50c62'
down_revision = '29048b05599'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('huoltosopimukset', sa.Column('ke_starting_date', sa.Date(), nullable=True))
    op.add_column('huoltosopimukset', sa.Column('sy_starting_date', sa.Date(), nullable=True))
    op.add_column('huoltosopimukset_version', sa.Column('ke_starting_date', sa.Date(), autoincrement=False, nullable=True))
    op.add_column('huoltosopimukset_version', sa.Column('sy_starting_date', sa.Date(), autoincrement=False, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('huoltosopimukset_version', 'sy_starting_date')
    op.drop_column('huoltosopimukset_version', 'ke_starting_date')
    op.drop_column('huoltosopimukset', 'sy_starting_date')
    op.drop_column('huoltosopimukset', 'ke_starting_date')
    ### end Alembic commands ###
