"""empty message

Revision ID: 26341e6a4a3
Revises: 227a705dee8
Create Date: 2015-02-08 21:43:00.288186

"""

# revision identifiers, used by Alembic.
revision = '26341e6a4a3'
down_revision = '227a705dee8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hintaluokat', sa.Column('muut', sa.Float(), nullable=True))
    op.alter_column('users', 'admin',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('users', 'vuosihuoltosopimukset',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'vuosihuoltosopimukset',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('users', 'admin',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('hintaluokat', 'muut')
    ### end Alembic commands ###
