"""empty message

Revision ID: 29048b05599
Revises: 3abed0a79ea
Create Date: 2015-09-14 19:58:52.124850

"""

# revision identifiers, used by Alembic.
revision = '29048b05599'
down_revision = '3abed0a79ea'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('huoltosopimukset', sa.Column('tk_interval_months', sa.Float(), nullable=True))
    op.add_column('huoltosopimukset', sa.Column('tk_starting_date', sa.Date(), nullable=True))
    op.drop_column('huoltosopimukset', 'tyyppi_ek')
    op.add_column('huoltosopimukset_version', sa.Column('tk_interval_months', sa.Float(), autoincrement=False, nullable=True))
    op.add_column('huoltosopimukset_version', sa.Column('tk_starting_date', sa.Date(), autoincrement=False, nullable=True))
    op.drop_column('huoltosopimukset_version', 'tyyppi_ek')
    op.alter_column('laitteet', 'valmistusvuosi',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('laitteet_version', 'valmistusvuosi',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('laitteet_version', 'valmistusvuosi',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.alter_column('laitteet', 'valmistusvuosi',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
    op.add_column('huoltosopimukset_version', sa.Column('tyyppi_ek', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('huoltosopimukset_version', 'tk_starting_date')
    op.drop_column('huoltosopimukset_version', 'tk_interval_months')
    op.add_column('huoltosopimukset', sa.Column('tyyppi_ek', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_column('huoltosopimukset', 'tk_starting_date')
    op.drop_column('huoltosopimukset', 'tk_interval_months')
    ### end Alembic commands ###
