"""empty message

Revision ID: 2b3abf61e8e
Revises: 53c06ab2a1
Create Date: 2014-08-25 23:55:57.497806

"""

# revision identifiers, used by Alembic.
revision = '2b3abf61e8e'
down_revision = '53c06ab2a1'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vesikalustekartoitukset',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('kohde_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['kohde_id'], ['kohteet.id'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('vkk_asunnot',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('vkk_uuid', sa.Integer(), nullable=True),
    sa.Column('numero', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['vkk_uuid'], ['vesikalustekartoitukset.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('vkk_huoneet',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('asunto_uuid', sa.Integer(), nullable=True),
    sa.Column('nimi', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['asunto_uuid'], ['vkk_asunnot.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('vkk_kalusteet',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('huone_uuid', sa.Integer(), nullable=True),
    sa.Column('nimi', sa.Text(), nullable=False),
    sa.Column('koodi', sa.Text(), nullable=True),
    sa.Column('maara', sa.Integer(), nullable=False),
    sa.Column('tila', sa.Enum('Korjaus', 'Vaihto', 'Ok', name='enum_kaluste_tila'), nullable=False),
    sa.ForeignKeyConstraint(['huone_uuid'], ['vkk_huoneet.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.drop_table('vk_tklistat')
    op.drop_table('laitteet')
    op.drop_column('kohteet', 'laitteet_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('kohteet', sa.Column('laitteet_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_table('laitteet',
    sa.Column('uuid', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=False),
    sa.Column('ljh_vaihdin', mysql.TEXT(), nullable=True),
    sa.Column('ljh_vaihdin_vm', mysql.TEXT(), nullable=True),
    sa.Column('klv_patteriverkosto', mysql.TEXT(), nullable=True),
    sa.Column('klv_lattialammitys', mysql.TEXT(), nullable=True),
    sa.Column('klv_ilmastointi', mysql.TEXT(), nullable=True),
    sa.Column('klv_kayttovesi', mysql.TEXT(), nullable=True),
    sa.Column('vv_patteriverkosto', mysql.TEXT(), nullable=True),
    sa.Column('vv_lattialammitys', mysql.TEXT(), nullable=True),
    sa.Column('vv_ilmastointi', mysql.TEXT(), nullable=True),
    sa.Column('vv_kayttovesi', mysql.TEXT(), nullable=True),
    sa.Column('pa_patteriverkosto', mysql.TEXT(), nullable=True),
    sa.Column('pa_lattialammitys', mysql.TEXT(), nullable=True),
    sa.Column('pa_ilmastointi', mysql.TEXT(), nullable=True),
    sa.Column('pa_kayttovesi', mysql.TEXT(), nullable=True),
    sa.Column('p_patteriverkosto', mysql.TEXT(), nullable=True),
    sa.Column('p_lattialammitys', mysql.TEXT(), nullable=True),
    sa.Column('p_ilmastointi', mysql.TEXT(), nullable=True),
    sa.Column('p_kayttovesi', mysql.TEXT(), nullable=True),
    sa.Column('s_patteriverkosto', mysql.TEXT(), nullable=True),
    sa.Column('s_lattialammitys', mysql.TEXT(), nullable=True),
    sa.Column('s_ilmastointi', mysql.TEXT(), nullable=True),
    sa.Column('s_kayttovesi', mysql.TEXT(), nullable=True),
    sa.Column('muu_huom', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('vk_tklistat',
    sa.Column('uuid', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('date', mysql.DATETIME(), nullable=False),
    sa.Column('kohde_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('este', mysql.TEXT(), nullable=True),
    sa.Column('sov_aika', mysql.TEXT(), nullable=True),
    sa.Column('k_sekottaja_tila', mysql.TEXT(), nullable=True),
    sa.Column('k_sekottaja_tp', mysql.TEXT(), nullable=True),
    sa.Column('k_sekottaja_selitys', mysql.TEXT(), nullable=True),
    sa.Column('k_pkhana_tila', mysql.TEXT(), nullable=True),
    sa.Column('k_pkhana_tp', mysql.TEXT(), nullable=True),
    sa.Column('k_pkhana_selitys', mysql.TEXT(), nullable=True),
    sa.Column('k_hajulukko_tila', mysql.TEXT(), nullable=True),
    sa.Column('k_hajulukko_tp', mysql.TEXT(), nullable=True),
    sa.Column('k_hajulukko_selitys', mysql.TEXT(), nullable=True),
    sa.Column('k_viemliitos_tila', mysql.TEXT(), nullable=True),
    sa.Column('k_viemliitos_tp', mysql.TEXT(), nullable=True),
    sa.Column('k_viemliitos_selitys', mysql.TEXT(), nullable=True),
    sa.Column('k_extra1_tila', mysql.TEXT(), nullable=True),
    sa.Column('k_extra1_tp', mysql.TEXT(), nullable=True),
    sa.Column('k_extra1_selitys', mysql.TEXT(), nullable=True),
    sa.Column('k_extra2_tila', mysql.TEXT(), nullable=True),
    sa.Column('k_extra2_tp', mysql.TEXT(), nullable=True),
    sa.Column('k_extra2_selitys', mysql.TEXT(), nullable=True),
    sa.Column('k_extra3_tila', mysql.TEXT(), nullable=True),
    sa.Column('k_extra3_tp', mysql.TEXT(), nullable=True),
    sa.Column('k_extra3_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc1_istuin_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc1_istuin_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc1_istuin_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc1_sulku_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc1_sulku_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc1_sulku_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc1_viemliitos_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc1_viemliitos_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc1_viemliitos_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc1_wcsisa_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc1_wcsisa_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc1_wcsisa_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc1_allassekottaja_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc1_allassekottaja_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc1_allassekottaja_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc1_suihkusekottaja_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc1_suihkusekottaja_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc1_suihkusekottaja_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc1_suihkuvarusteet_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc1_suihkuvarusteet_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc1_suihkuvarusteet_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc1_pkhana_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc1_pkhana_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc1_pkhana_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc1_vesilukko_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc1_vesilukko_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc1_vesilukko_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc1_lattiakaivo_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc1_lattiakaivo_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc1_lattiakaivo_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc1_kuivakaivo_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc1_kuivakaivo_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc1_kuivakaivo_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc1_kvpatteri_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc1_kvpatteri_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc1_kvpatteri_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc1_extra1_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc1_extra1_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc1_extra1_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc1_extra2_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc1_extra2_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc1_extra2_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc1_extra3_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc1_extra3_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc1_extra3_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc1_wcmalli', mysql.TEXT(), nullable=True),
    sa.Column('wc2_istuin_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc2_istuin_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc2_istuin_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc2_sulku_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc2_sulku_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc2_sulku_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc2_viemliitos_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc2_viemliitos_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc2_viemliitos_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc2_wcsisa_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc2_wcsisa_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc2_wcsisa_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc2_allassekottaja_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc2_allassekottaja_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc2_allassekottaja_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc2_extra1_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc2_extra1_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc2_extra1_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc2_extra2_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc2_extra2_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc2_extra2_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc2_extra3_tila', mysql.TEXT(), nullable=True),
    sa.Column('wc2_extra3_tp', mysql.TEXT(), nullable=True),
    sa.Column('wc2_extra3_selitys', mysql.TEXT(), nullable=True),
    sa.Column('wc2_wcmalli', mysql.TEXT(), nullable=True),
    sa.Column('huomiot', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['kohde_id'], ['kohteet.uuid'], name='vk_tklistat_ibfk_1'),
    sa.PrimaryKeyConstraint('uuid'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.drop_table('vkk_kalusteet')
    op.drop_table('vkk_huoneet')
    op.drop_table('vkk_asunnot')
    op.drop_table('vesikalustekartoitukset')
    ### end Alembic commands ###
