"""empty message

Revision ID: 352816628c6
Revises: cb81493ed4
Create Date: 2014-08-11 00:29:08.647181

"""

# revision identifiers, used by Alembic.
revision = '352816628c6'
down_revision = 'cb81493ed4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('vuosihuoltosopimukset', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'vuosihuoltosopimukset')
    ### end Alembic commands ###
