"""empty message

Revision ID: 39d57e0bdb4
Revises: 452a6faae00
Create Date: 2015-09-26 18:44:27.934998

"""

# revision identifiers, used by Alembic.
revision = '39d57e0bdb4'
down_revision = '452a6faae00'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('huoltohintaluokat',
    sa.Column('hintaluokka', sa.Integer(), nullable=False),
    sa.Column('ek', sa.Float(), nullable=True),
    sa.Column('ke', sa.Float(), nullable=True),
    sa.Column('sy', sa.Float(), nullable=True),
    sa.Column('tk', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('hintaluokka')
    )
    op.create_table('lisatoimenpidehintaluokka',
    sa.Column('hintaluokka', sa.Integer(), nullable=False),
    sa.Column('tunnit', sa.Float(), nullable=True),
    sa.Column('matkat', sa.Float(), nullable=True),
    sa.Column('muut', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('hintaluokka')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lisatoimenpidehintaluokka')
    op.drop_table('huoltohintaluokat')
    ### end Alembic commands ###
