"""empty message

Revision ID: 3abed0a79ea
Revises: 43087ffab4b
Create Date: 2015-09-06 06:10:50.998200

"""

# revision identifiers, used by Alembic.
revision = '3abed0a79ea'
down_revision = '43087ffab4b'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lisatoimenpiteet_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('huolto_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('teksti', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('hintaluokka', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('tunnit', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('matkat', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('muut', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_lisatoimenpiteet_version_end_transaction_id'), 'lisatoimenpiteet_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_lisatoimenpiteet_version_operation_type'), 'lisatoimenpiteet_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_lisatoimenpiteet_version_transaction_id'), 'lisatoimenpiteet_version', ['transaction_id'], unique=False)
    op.create_table('lisatoimenpiteet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('huolto_id', sa.Integer(), nullable=True),
    sa.Column('teksti', sa.Text(), nullable=True),
    sa.Column('hintaluokka', sa.Integer(), nullable=False),
    sa.Column('tunnit', sa.Float(), nullable=True),
    sa.Column('matkat', sa.Float(), nullable=True),
    sa.Column('muut', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['huolto_id'], ['huollot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('huoltorapotit', sa.Column('korjaustarve', sa.Boolean(), nullable=True))
    op.drop_column('huoltorapotit', 'muut')
    op.drop_column('huoltorapotit', 'tunnit')
    op.drop_column('huoltorapotit', 'hintaluokka')
    op.drop_column('huoltorapotit', 'matkat')
    op.add_column('huoltorapotit_version', sa.Column('korjaustarve', sa.Boolean(), autoincrement=False, nullable=True))
    op.drop_column('huoltorapotit_version', 'muut')
    op.drop_column('huoltorapotit_version', 'tunnit')
    op.drop_column('huoltorapotit_version', 'hintaluokka')
    op.drop_column('huoltorapotit_version', 'matkat')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('huoltorapotit_version', sa.Column('matkat', mysql.FLOAT(), nullable=True))
    op.add_column('huoltorapotit_version', sa.Column('hintaluokka', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('huoltorapotit_version', sa.Column('tunnit', mysql.FLOAT(), nullable=True))
    op.add_column('huoltorapotit_version', sa.Column('muut', mysql.FLOAT(), nullable=True))
    op.drop_column('huoltorapotit_version', 'korjaustarve')
    op.add_column('huoltorapotit', sa.Column('matkat', mysql.FLOAT(), nullable=True))
    op.add_column('huoltorapotit', sa.Column('hintaluokka', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('huoltorapotit', sa.Column('tunnit', mysql.FLOAT(), nullable=True))
    op.add_column('huoltorapotit', sa.Column('muut', mysql.FLOAT(), nullable=True))
    op.drop_column('huoltorapotit', 'korjaustarve')
    op.drop_table('lisatoimenpiteet')
    op.drop_index(op.f('ix_lisatoimenpiteet_version_transaction_id'), table_name='lisatoimenpiteet_version')
    op.drop_index(op.f('ix_lisatoimenpiteet_version_operation_type'), table_name='lisatoimenpiteet_version')
    op.drop_index(op.f('ix_lisatoimenpiteet_version_end_transaction_id'), table_name='lisatoimenpiteet_version')
    op.drop_table('lisatoimenpiteet_version')
    ### end Alembic commands ###
