"""empty message

Revision ID: 3e725f8c8ac
Revises: 553b8ac562f
Create Date: 2015-08-25 17:44:58.053274

"""

# revision identifiers, used by Alembic.
revision = '3e725f8c8ac'
down_revision = '553b8ac562f'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('huollot', 'viitenumero')
    op.drop_column('huollot_version', 'viitenumero')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('huollot_version', sa.Column('viitenumero', mysql.TEXT(), nullable=True))
    op.add_column('huollot', sa.Column('viitenumero', mysql.TEXT(), nullable=True))
    ### end Alembic commands ###
