"""Added new models

Revision ID: 42129b3413e
Revises: 17da5d1bd91
Create Date: 2014-06-22 01:29:05.320599

"""

# revision identifiers, used by Alembic.
revision = '42129b3413e'
down_revision = '17da5d1bd91'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laitteet',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('ljh_vaihdin', sa.Text(), nullable=True),
    sa.Column('ljh_vaihdin_vm', sa.Text(), nullable=True),
    sa.Column('klv_patteriverkosto', sa.Text(), nullable=True),
    sa.Column('klv_lattialammitys', sa.Text(), nullable=True),
    sa.Column('klv_ilmastointi', sa.Text(), nullable=True),
    sa.Column('klv_kayttovesi', sa.Text(), nullable=True),
    sa.Column('vv_patteriverkosto', sa.Text(), nullable=True),
    sa.Column('vv_lattialammitys', sa.Text(), nullable=True),
    sa.Column('vv_ilmastointi', sa.Text(), nullable=True),
    sa.Column('vv_kayttovesi', sa.Text(), nullable=True),
    sa.Column('pa_patteriverkosto', sa.Text(), nullable=True),
    sa.Column('pa_lattialammitys', sa.Text(), nullable=True),
    sa.Column('pa_ilmastointi', sa.Text(), nullable=True),
    sa.Column('pa_kayttovesi', sa.Text(), nullable=True),
    sa.Column('p_patteriverkosto', sa.Text(), nullable=True),
    sa.Column('p_lattialammitys', sa.Text(), nullable=True),
    sa.Column('p_ilmastointi', sa.Text(), nullable=True),
    sa.Column('p_kayttovesi', sa.Text(), nullable=True),
    sa.Column('s_patteriverkosto', sa.Text(), nullable=True),
    sa.Column('s_lattialammitys', sa.Text(), nullable=True),
    sa.Column('s_ilmastointi', sa.Text(), nullable=True),
    sa.Column('s_kayttovesi', sa.Text(), nullable=True),
    sa.Column('muu_huom', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('vk_tklistat',
    sa.Column('uuid', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('kohde_id', sa.Integer(), nullable=True),
    sa.Column('este', sa.Text(), nullable=True),
    sa.Column('sov_aika', sa.Text(), nullable=True),
    sa.Column('k_sekottaja_tila', sa.Text(), nullable=True),
    sa.Column('k_sekottaja_tp', sa.Text(), nullable=True),
    sa.Column('k_sekottaja_selitys', sa.Text(), nullable=True),
    sa.Column('k_pkhana_tila', sa.Text(), nullable=True),
    sa.Column('k_pkhana_tp', sa.Text(), nullable=True),
    sa.Column('k_pkhana_selitys', sa.Text(), nullable=True),
    sa.Column('k_hajulukko_tila', sa.Text(), nullable=True),
    sa.Column('k_hajulukko_tp', sa.Text(), nullable=True),
    sa.Column('k_hajulukko_selitys', sa.Text(), nullable=True),
    sa.Column('k_viemliitos_tila', sa.Text(), nullable=True),
    sa.Column('k_viemliitos_tp', sa.Text(), nullable=True),
    sa.Column('k_viemliitos_selitys', sa.Text(), nullable=True),
    sa.Column('k_extra1_tila', sa.Text(), nullable=True),
    sa.Column('k_extra1_tp', sa.Text(), nullable=True),
    sa.Column('k_extra1_selitys', sa.Text(), nullable=True),
    sa.Column('k_extra2_tila', sa.Text(), nullable=True),
    sa.Column('k_extra2_tp', sa.Text(), nullable=True),
    sa.Column('k_extra2_selitys', sa.Text(), nullable=True),
    sa.Column('k_extra3_tila', sa.Text(), nullable=True),
    sa.Column('k_extra3_tp', sa.Text(), nullable=True),
    sa.Column('k_extra3_selitys', sa.Text(), nullable=True),
    sa.Column('wc1_istuin_tila', sa.Text(), nullable=True),
    sa.Column('wc1_istuin_tp', sa.Text(), nullable=True),
    sa.Column('wc1_istuin_selitys', sa.Text(), nullable=True),
    sa.Column('wc1_sulku_tila', sa.Text(), nullable=True),
    sa.Column('wc1_sulku_tp', sa.Text(), nullable=True),
    sa.Column('wc1_sulku_selitys', sa.Text(), nullable=True),
    sa.Column('wc1_viemliitos_tila', sa.Text(), nullable=True),
    sa.Column('wc1_viemliitos_tp', sa.Text(), nullable=True),
    sa.Column('wc1_viemliitos_selitys', sa.Text(), nullable=True),
    sa.Column('wc1_wcsisa_tila', sa.Text(), nullable=True),
    sa.Column('wc1_wcsisa_tp', sa.Text(), nullable=True),
    sa.Column('wc1_wcsisa_selitys', sa.Text(), nullable=True),
    sa.Column('wc1_allassekottaja_tila', sa.Text(), nullable=True),
    sa.Column('wc1_allassekottaja_tp', sa.Text(), nullable=True),
    sa.Column('wc1_allassekottaja_selitys', sa.Text(), nullable=True),
    sa.Column('wc1_suihkusekottaja_tila', sa.Text(), nullable=True),
    sa.Column('wc1_suihkusekottaja_tp', sa.Text(), nullable=True),
    sa.Column('wc1_suihkusekottaja_selitys', sa.Text(), nullable=True),
    sa.Column('wc1_suihkuvarusteet_tila', sa.Text(), nullable=True),
    sa.Column('wc1_suihkuvarusteet_tp', sa.Text(), nullable=True),
    sa.Column('wc1_suihkuvarusteet_selitys', sa.Text(), nullable=True),
    sa.Column('wc1_pkhana_tila', sa.Text(), nullable=True),
    sa.Column('wc1_pkhana_tp', sa.Text(), nullable=True),
    sa.Column('wc1_pkhana_selitys', sa.Text(), nullable=True),
    sa.Column('wc1_vesilukko_tila', sa.Text(), nullable=True),
    sa.Column('wc1_vesilukko_tp', sa.Text(), nullable=True),
    sa.Column('wc1_vesilukko_selitys', sa.Text(), nullable=True),
    sa.Column('wc1_lattiakaivo_tila', sa.Text(), nullable=True),
    sa.Column('wc1_lattiakaivo_tp', sa.Text(), nullable=True),
    sa.Column('wc1_lattiakaivo_selitys', sa.Text(), nullable=True),
    sa.Column('wc1_kuivakaivo_tila', sa.Text(), nullable=True),
    sa.Column('wc1_kuivakaivo_tp', sa.Text(), nullable=True),
    sa.Column('wc1_kuivakaivo_selitys', sa.Text(), nullable=True),
    sa.Column('wc1_kvpatteri_tila', sa.Text(), nullable=True),
    sa.Column('wc1_kvpatteri_tp', sa.Text(), nullable=True),
    sa.Column('wc1_kvpatteri_selitys', sa.Text(), nullable=True),
    sa.Column('wc1_extra1_tila', sa.Text(), nullable=True),
    sa.Column('wc1_extra1_tp', sa.Text(), nullable=True),
    sa.Column('wc1_extra1_selitys', sa.Text(), nullable=True),
    sa.Column('wc1_extra2_tila', sa.Text(), nullable=True),
    sa.Column('wc1_extra2_tp', sa.Text(), nullable=True),
    sa.Column('wc1_extra2_selitys', sa.Text(), nullable=True),
    sa.Column('wc1_extra3_tila', sa.Text(), nullable=True),
    sa.Column('wc1_extra3_tp', sa.Text(), nullable=True),
    sa.Column('wc1_extra3_selitys', sa.Text(), nullable=True),
    sa.Column('wc1_wcmalli', sa.Text(), nullable=True),
    sa.Column('wc2_istuin_tila', sa.Text(), nullable=True),
    sa.Column('wc2_istuin_tp', sa.Text(), nullable=True),
    sa.Column('wc2_istuin_selitys', sa.Text(), nullable=True),
    sa.Column('wc2_sulku_tila', sa.Text(), nullable=True),
    sa.Column('wc2_sulku_tp', sa.Text(), nullable=True),
    sa.Column('wc2_sulku_selitys', sa.Text(), nullable=True),
    sa.Column('wc2_viemliitos_tila', sa.Text(), nullable=True),
    sa.Column('wc2_viemliitos_tp', sa.Text(), nullable=True),
    sa.Column('wc2_viemliitos_selitys', sa.Text(), nullable=True),
    sa.Column('wc2_wcsisa_tila', sa.Text(), nullable=True),
    sa.Column('wc2_wcsisa_tp', sa.Text(), nullable=True),
    sa.Column('wc2_wcsisa_selitys', sa.Text(), nullable=True),
    sa.Column('wc2_allassekottaja_tila', sa.Text(), nullable=True),
    sa.Column('wc2_allassekottaja_tp', sa.Text(), nullable=True),
    sa.Column('wc2_allassekottaja_selitys', sa.Text(), nullable=True),
    sa.Column('wc2_extra1_tila', sa.Text(), nullable=True),
    sa.Column('wc2_extra1_tp', sa.Text(), nullable=True),
    sa.Column('wc2_extra1_selitys', sa.Text(), nullable=True),
    sa.Column('wc2_extra2_tila', sa.Text(), nullable=True),
    sa.Column('wc2_extra2_tp', sa.Text(), nullable=True),
    sa.Column('wc2_extra2_selitys', sa.Text(), nullable=True),
    sa.Column('wc2_extra3_tila', sa.Text(), nullable=True),
    sa.Column('wc2_extra3_tp', sa.Text(), nullable=True),
    sa.Column('wc2_extra3_selitys', sa.Text(), nullable=True),
    sa.Column('wc2_wcmalli', sa.Text(), nullable=True),
    sa.Column('huomiot', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['kohde_id'], ['kohteet.uuid'], ),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.add_column('kohteet', sa.Column('laitteet_id', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('kohteet', 'laitteet_id')
    op.drop_table('vk_tklistat')
    op.drop_table('laitteet')
    ### end Alembic commands ###
