"""empty message

Revision ID: 43087ffab4b
Revises: 3e725f8c8ac
Create Date: 2015-08-30 11:42:14.260950

"""

# revision identifiers, used by Alembic.
revision = '43087ffab4b'
down_revision = '3e725f8c8ac'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laitteet', sa.Column('tyyppitiedot', sa.Text(), nullable=True))
    op.add_column('laitteet', sa.Column('valmistusvuosi', sa.Float(), nullable=True))
    op.drop_column('laitteet', 'yksikko')
    op.drop_column('laitteet', 'hinta')
    op.drop_column('laitteet', 'koodi')
    op.add_column('laitteet_version', sa.Column('tyyppitiedot', sa.Text(), autoincrement=False, nullable=True))
    op.add_column('laitteet_version', sa.Column('valmistusvuosi', sa.Float(), autoincrement=False, nullable=True))
    op.drop_column('laitteet_version', 'yksikko')
    op.drop_column('laitteet_version', 'hinta')
    op.drop_column('laitteet_version', 'koodi')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laitteet_version', sa.Column('koodi', mysql.TEXT(), nullable=True))
    op.add_column('laitteet_version', sa.Column('hinta', mysql.FLOAT(), nullable=True))
    op.add_column('laitteet_version', sa.Column('yksikko', mysql.TEXT(), nullable=True))
    op.drop_column('laitteet_version', 'valmistusvuosi')
    op.drop_column('laitteet_version', 'tyyppitiedot')
    op.add_column('laitteet', sa.Column('koodi', mysql.TEXT(), nullable=True))
    op.add_column('laitteet', sa.Column('hinta', mysql.FLOAT(), nullable=True))
    op.add_column('laitteet', sa.Column('yksikko', mysql.TEXT(), nullable=True))
    op.drop_column('laitteet', 'valmistusvuosi')
    op.drop_column('laitteet', 'tyyppitiedot')
    ### end Alembic commands ###
