"""empty message

Revision ID: 434977d7e52
Revises: 577c88fd031
Create Date: 2014-12-29 23:03:43.599549

"""

# revision identifiers, used by Alembic.
revision = '434977d7e52'
down_revision = '577c88fd031'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paivarapotit', sa.Column('hintaluokka', sa.Integer(), nullable=False, server_default='2'))
    op.add_column('paivarapotit_version', sa.Column('hintaluokka', sa.Integer(), autoincrement=False, nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paivarapotit_version', 'hintaluokka')
    op.drop_column('paivarapotit', 'hintaluokka')
    ### end Alembic commands ###
