"""empty message

Revision ID: 452a6faae00
Revises: 2630fa50c62
Create Date: 2015-09-14 20:06:06.504389

"""

# revision identifiers, used by Alembic.
revision = '452a6faae00'
down_revision = '2630fa50c62'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###

    op.add_column('kohteet', sa.Column('slaskutus', sa.Text(), nullable=True))
    op.add_column('kohteet_version', sa.Column('slaskutus', sa.Text(), autoincrement=False, nullable=True))

    connection = op.get_bind()

    for tilaus in connection.execute("SELECT tilaaja_id, kohde_id FROM tilaukset"):
        connection.execute("UPDATE kohteet, tilaajat"
                           " SET kohteet.slaskutus = tilaajat.slaskutus"
                           " WHERE tilaajat.id = " + str(tilaus.tilaaja_id) +
                           " AND kohteet.id = " + str(tilaus.kohde_id))

    op.drop_column('tilaajat', 'slaskutus')
    op.drop_column('tilaajat_version', 'slaskutus')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tilaajat_version', sa.Column('slaskutus', mysql.TEXT(), nullable=True))
    op.add_column('tilaajat', sa.Column('slaskutus', mysql.TEXT(), nullable=True))

    connection = op.get_bind()

    for tilaus in connection.execute("SELECT tilaaja_id, kohde_id FROM tilaukset"):
        connection.execute("UPDATE kohteet, tilaajat"
                           " SET tilaajat.slaskutus = kohteet.slaskutus"
                           " WHERE tilaajat.id = " + str(tilaus.tilaaja_id) +
                           " AND kohteet.id = " + str(tilaus.kohde_id))

    op.drop_column('kohteet_version', 'slaskutus')
    op.drop_column('kohteet', 'slaskutus')
    ### end Alembic commands ###
