"""empty message

Revision ID: 4a81e505ae1
Revises: 26341e6a4a3
Create Date: 2015-02-24 19:21:59.249060

"""

# revision identifiers, used by Alembic.
revision = '4a81e505ae1'
down_revision = '26341e6a4a3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tavarat', sa.Column('yksikko', sa.Text(), nullable=True))
    op.add_column('tavarat_version', sa.Column('yksikko', sa.Text(), autoincrement=False, nullable=True))
    op.alter_column('users', 'admin',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('users', 'vuosihuoltosopimukset',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'vuosihuoltosopimukset',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('users', 'admin',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_column('tavarat_version', 'yksikko')
    op.drop_column('tavarat', 'yksikko')
    ### end Alembic commands ###
