"""empty message

Revision ID: 53c06ab2a1
Revises: 1d323e2bdcb
Create Date: 2014-08-22 00:29:09.987824

"""

# revision identifiers, used by Alembic.
revision = '53c06ab2a1'
down_revision = '1d323e2bdcb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tavarat', sa.Column('hinta', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tavarat', 'hinta')
    ### end Alembic commands ###
