"""empty message

Revision ID: 553b8ac562f
Revises: 310d4500779
Create Date: 2015-08-06 20:15:26.207330

"""

# revision identifiers, used by Alembic.
revision = '553b8ac562f'
down_revision = '310d4500779'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('huoltorapotit_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('huolto_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('teksti', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('hintaluokka', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('tunnit', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('matkat', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('muut', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_huoltorapotit_version_end_transaction_id'), 'huoltorapotit_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_huoltorapotit_version_operation_type'), 'huoltorapotit_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_huoltorapotit_version_transaction_id'), 'huoltorapotit_version', ['transaction_id'], unique=False)
    op.create_table('laiteluettelot_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('huoltosopimus_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_laiteluettelot_version_end_transaction_id'), 'laiteluettelot_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_laiteluettelot_version_operation_type'), 'laiteluettelot_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_laiteluettelot_version_transaction_id'), 'laiteluettelot_version', ['transaction_id'], unique=False)
    op.create_table('laitteet_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('tavaraluettelo_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('koodi', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('nimi', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('hinta', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('maara', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('yksikko', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('tyyppi', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_laitteet_version_end_transaction_id'), 'laitteet_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_laitteet_version_operation_type'), 'laitteet_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_laitteet_version_transaction_id'), 'laitteet_version', ['transaction_id'], unique=False)
    op.create_table('huollot_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('tila', sa.String(length=15), autoincrement=False, nullable=True),
    sa.Column('viitenumero', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('huoltosopimus_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('tyyppi', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('laiteluettelo_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_huollot_version_end_transaction_id'), 'huollot_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_huollot_version_operation_type'), 'huollot_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_huollot_version_transaction_id'), 'huollot_version', ['transaction_id'], unique=False)
    op.create_table('laiteluettelot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('huoltosopimus_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['huoltosopimus_id'], ['huoltosopimukset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('huollot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('tila', sa.String(length=15), nullable=False),
    sa.Column('viitenumero', sa.Text(), nullable=True),
    sa.Column('huoltosopimus_id', sa.Integer(), nullable=True),
    sa.Column('tyyppi', sa.Text(), nullable=True),
    sa.Column('laiteluettelo_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['huoltosopimus_id'], ['huoltosopimukset.id'], ),
    sa.ForeignKeyConstraint(['laiteluettelo_id'], ['laiteluettelot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laitteet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('tavaraluettelo_id', sa.Integer(), nullable=True),
    sa.Column('koodi', sa.Text(), nullable=True),
    sa.Column('nimi', sa.Text(), nullable=True),
    sa.Column('hinta', sa.Float(), nullable=True),
    sa.Column('maara', sa.Float(), nullable=True),
    sa.Column('yksikko', sa.Text(), nullable=True),
    sa.Column('tyyppi', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tavaraluettelo_id'], ['laiteluettelot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('huoltorapotit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('huolto_id', sa.Integer(), nullable=True),
    sa.Column('teksti', sa.Text(), nullable=True),
    sa.Column('hintaluokka', sa.Integer(), nullable=False),
    sa.Column('tunnit', sa.Float(), nullable=True),
    sa.Column('matkat', sa.Float(), nullable=True),
    sa.Column('muut', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['huolto_id'], ['huollot.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('huoltosopimukset', 'tyyppi_ek',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('huoltosopimukset', 'tyyppi_ke',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('huoltosopimukset', 'tyyppi_sy',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('huoltosopimukset', 'tyyppi_tk',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('huoltosopimukset_version', 'tyyppi_ek',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('huoltosopimukset_version', 'tyyppi_ke',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('huoltosopimukset_version', 'tyyppi_sy',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('huoltosopimukset_version', 'tyyppi_tk',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('users', 'admin',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.alter_column('users', 'vuosihuoltosopimukset',
               existing_type=mysql.TINYINT(display_width=1),
               type_=sa.Boolean(),
               existing_nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'vuosihuoltosopimukset',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('users', 'admin',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('huoltosopimukset_version', 'tyyppi_tk',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('huoltosopimukset_version', 'tyyppi_sy',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('huoltosopimukset_version', 'tyyppi_ke',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('huoltosopimukset_version', 'tyyppi_ek',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('huoltosopimukset', 'tyyppi_tk',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('huoltosopimukset', 'tyyppi_sy',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('huoltosopimukset', 'tyyppi_ke',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('huoltosopimukset', 'tyyppi_ek',
               existing_type=sa.Boolean(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.drop_table('huoltorapotit')
    op.drop_table('laitteet')
    op.drop_table('huollot')
    op.drop_table('laiteluettelot')
    op.drop_index(op.f('ix_huollot_version_transaction_id'), table_name='huollot_version')
    op.drop_index(op.f('ix_huollot_version_operation_type'), table_name='huollot_version')
    op.drop_index(op.f('ix_huollot_version_end_transaction_id'), table_name='huollot_version')
    op.drop_table('huollot_version')
    op.drop_index(op.f('ix_laitteet_version_transaction_id'), table_name='laitteet_version')
    op.drop_index(op.f('ix_laitteet_version_operation_type'), table_name='laitteet_version')
    op.drop_index(op.f('ix_laitteet_version_end_transaction_id'), table_name='laitteet_version')
    op.drop_table('laitteet_version')
    op.drop_index(op.f('ix_laiteluettelot_version_transaction_id'), table_name='laiteluettelot_version')
    op.drop_index(op.f('ix_laiteluettelot_version_operation_type'), table_name='laiteluettelot_version')
    op.drop_index(op.f('ix_laiteluettelot_version_end_transaction_id'), table_name='laiteluettelot_version')
    op.drop_table('laiteluettelot_version')
    op.drop_index(op.f('ix_huoltorapotit_version_transaction_id'), table_name='huoltorapotit_version')
    op.drop_index(op.f('ix_huoltorapotit_version_operation_type'), table_name='huoltorapotit_version')
    op.drop_index(op.f('ix_huoltorapotit_version_end_transaction_id'), table_name='huoltorapotit_version')
    op.drop_table('huoltorapotit_version')
    ### end Alembic commands ###
