"""empty message

Revision ID: 577c88fd031
Revises: 32a4c053e56
Create Date: 2014-12-08 04:07:03.523663

"""

# revision identifiers, used by Alembic.
revision = '577c88fd031'
down_revision = '32a4c053e56'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tilaukset', sa.Column('tila', sa.String(length=15), nullable=False))
    op.add_column('tilaukset_version', sa.Column('tila', sa.String(length=15), autoincrement=False, nullable=True, server_default="UUSI"))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tilaukset_version', 'tila')
    op.drop_column('tilaukset', 'tila')
    ### end Alembic commands ###
