"""add missing versioning

Revision ID: 635547660b0e
Revises: 93e1e6d17e0c
Create Date: 2023-11-14 18:15:01.608453

"""

# revision identifiers, used by Alembic.
revision = '635547660b0e'
down_revision = '93e1e6d17e0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hintaluokat_version',
    sa.Column('hintaluokka', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('tunnit', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('matkat', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('muut', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('hintaluokka', 'transaction_id')
    )
    op.create_index(op.f('ix_hintaluokat_version_end_transaction_id'), 'hintaluokat_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_hintaluokat_version_operation_type'), 'hintaluokat_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_hintaluokat_version_transaction_id'), 'hintaluokat_version', ['transaction_id'], unique=False)
    op.create_table('huoltohintaluokat_version',
    sa.Column('hintaluokka', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('ek', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('ke', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('sy', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('tk', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('hintaluokka', 'transaction_id')
    )
    op.create_index(op.f('ix_huoltohintaluokat_version_end_transaction_id'), 'huoltohintaluokat_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_huoltohintaluokat_version_operation_type'), 'huoltohintaluokat_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_huoltohintaluokat_version_transaction_id'), 'huoltohintaluokat_version', ['transaction_id'], unique=False)
    op.create_table('lisatoimenpidehintaluokat_version',
    sa.Column('hintaluokka', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('tunnit', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('matkat', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('muut', sa.Float(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('hintaluokka', 'transaction_id')
    )
    op.create_index(op.f('ix_lisatoimenpidehintaluokat_version_end_transaction_id'), 'lisatoimenpidehintaluokat_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_lisatoimenpidehintaluokat_version_operation_type'), 'lisatoimenpidehintaluokat_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_lisatoimenpidehintaluokat_version_transaction_id'), 'lisatoimenpidehintaluokat_version', ['transaction_id'], unique=False)
    op.create_table('users_version',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DateTime(), autoincrement=False, nullable=True),
    sa.Column('name', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('email', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.Text(), autoincrement=False, nullable=True),
    sa.Column('tilaaja_id', sa.Integer(), autoincrement=False, nullable=True),
    sa.Column('admin', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('vuosihuoltosopimukset', sa.Boolean(), autoincrement=False, nullable=True),
    sa.Column('transaction_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('end_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('operation_type', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'transaction_id')
    )
    op.create_index(op.f('ix_users_version_end_transaction_id'), 'users_version', ['end_transaction_id'], unique=False)
    op.create_index(op.f('ix_users_version_operation_type'), 'users_version', ['operation_type'], unique=False)
    op.create_index(op.f('ix_users_version_transaction_id'), 'users_version', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_version_transaction_id'), table_name='users_version')
    op.drop_index(op.f('ix_users_version_operation_type'), table_name='users_version')
    op.drop_index(op.f('ix_users_version_end_transaction_id'), table_name='users_version')
    op.drop_table('users_version')
    op.drop_index(op.f('ix_lisatoimenpidehintaluokat_version_transaction_id'), table_name='lisatoimenpidehintaluokat_version')
    op.drop_index(op.f('ix_lisatoimenpidehintaluokat_version_operation_type'), table_name='lisatoimenpidehintaluokat_version')
    op.drop_index(op.f('ix_lisatoimenpidehintaluokat_version_end_transaction_id'), table_name='lisatoimenpidehintaluokat_version')
    op.drop_table('lisatoimenpidehintaluokat_version')
    op.drop_index(op.f('ix_huoltohintaluokat_version_transaction_id'), table_name='huoltohintaluokat_version')
    op.drop_index(op.f('ix_huoltohintaluokat_version_operation_type'), table_name='huoltohintaluokat_version')
    op.drop_index(op.f('ix_huoltohintaluokat_version_end_transaction_id'), table_name='huoltohintaluokat_version')
    op.drop_table('huoltohintaluokat_version')
    op.drop_index(op.f('ix_hintaluokat_version_transaction_id'), table_name='hintaluokat_version')
    op.drop_index(op.f('ix_hintaluokat_version_operation_type'), table_name='hintaluokat_version')
    op.drop_index(op.f('ix_hintaluokat_version_end_transaction_id'), table_name='hintaluokat_version')
    op.drop_table('hintaluokat_version')
    # ### end Alembic commands ###
