"""empty message

Revision ID: 93e1e6d17e0c
Revises: 05611c3d1c30
Create Date: 2017-09-10 19:13:49.931602

"""

# revision identifiers, used by Alembic.
revision = '93e1e6d17e0c'
down_revision = '05611c3d1c30'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('huoltosopimukset', sa.Column('ke_next_date', sa.Date(), nullable=True))
    op.add_column('huoltosopimukset', sa.Column('sy_next_date', sa.Date(), nullable=True))
    op.add_column('huoltosopimukset', sa.Column('tk_next_date', sa.Date(), nullable=True))
    op.add_column('huoltosopimukset_version', sa.Column('ke_next_date', sa.Date(), autoincrement=False, nullable=True))
    op.add_column('huoltosopimukset_version', sa.Column('sy_next_date', sa.Date(), autoincrement=False, nullable=True))
    op.add_column('huoltosopimukset_version', sa.Column('tk_next_date', sa.Date(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('huoltosopimukset_version', 'tk_next_date')
    op.drop_column('huoltosopimukset_version', 'sy_next_date')
    op.drop_column('huoltosopimukset_version', 'ke_next_date')
    op.drop_column('huoltosopimukset', 'tk_next_date')
    op.drop_column('huoltosopimukset', 'sy_next_date')
    op.drop_column('huoltosopimukset', 'ke_next_date')
    # ### end Alembic commands ###
