"""empty message

Revision ID: f052370cdfa4
Revises: 19027df648c
Create Date: 2016-02-04 00:17:11.590101

"""

# revision identifiers, used by Alembic.
revision = 'f052370cdfa4'
down_revision = '19027df648c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('tilaaja_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'tilaajat', ['tilaaja_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'tilaaja_id')
    ### end Alembic commands ###
